### ISSUE TITLE
一个问题跟一个建议

### ISSUE THREAD

**Issue by yongming9011** [yushiwo/Universal-Image-Selector#1]
功能做的挺好的，有一个问题：预览已经加载到九宫格的图片，点击右上角删除按钮，删除完图片后如果点击左上角返回按钮返回则已经删除的图片会从九宫格移除，如果点击的是物理按键返回，则已经删除的图片依然还在九宫格中。一个建议，建议选择图片时，右下角可以显示为  1/9,2/9实时显示已选择的张数跟总数。感谢作者的分享与奉献！

**Comment by yushiwo** [comment]
谢谢你提的问题，在新版本里面解决了哈。
